language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
  #install sratoolkit
  - wget https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/current/sratoolkit.current-ubuntu64.tar.gz -O /tmp/sratools.tar.gz
  - tar -xvzf /tmp/sratools.tar.gz
  - export PATH=$PATH:$PWD/sratoolkit.2.9.6-1-ubuntu64/bin/
  #install 
  - wget http://ccb.jhu.edu/software/stringtie/dl/stringtie-2.0.6.Linux_x86_64.tar.gz -O /tmp/stie.tar.gz
  - tar -xvzf /tmp/stie.tar.gz
  - export PATH=$PATH:$PWD/stringtie-2.0.6.Linux_x86_64/
# command to run tests
script:
  - pytest